/**
 * Initial Emergency Shift & Resident Dataset
 * Extracted directly from official Google Sheet
 */
window.DEFAULT_EMERGENCY_DATA = {
  "hospitalName": "مستشفى الصدر التعليمي",
  "monthYear": "أيلول 2026",
  "month": 9,
  "year": 2026,
  "residents": [
    {
      "id": "res_4",
      "name": "د. عماد سمير عبدالرضا",
      "notes": "END OF SERIVE is on 30/09/2026",
      "dc_target": 2,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 2,
      "stage": "3.0",
      "board": "Arabic",
      "specialty": "Cardiothoracic",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_5",
      "name": "د. شهد كريم عبدالكاظم",
      "notes": "PRIMARY EXAMINATION",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "2.0",
      "board": "-",
      "specialty": "Cardiothoracic",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_6",
      "name": "د. علي حسين عبدالرضا",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 2,
      "stage": "2.0",
      "board": "Arabic",
      "specialty": "Cardiothoracic",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_7",
      "name": "د. ايهاب عبدالكريم غالب",
      "notes": "",
      "dc_target": 2,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 3,
      "stage": "0.0",
      "board": "-",
      "specialty": "Cardiothoracic",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_8",
      "name": "د. رامي مهند عبدالله",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "",
      "board": "",
      "specialty": "Cardiothoracic",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_9",
      "name": "د. علي عبدالرحمن عبدالصمد",
      "notes": "HAS EXTRA ER",
      "dc_target": 2,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 3,
      "stage": "0.0",
      "board": "",
      "specialty": "Cardiothoracic",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_10",
      "name": "د. حسين علي عاشور",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "",
      "board": "",
      "specialty": "Cardiothoracic",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_11",
      "name": "د. همام حبيب عبدالله",
      "notes": "",
      "dc_target": 0,
      "con_target": 3,
      "rs_target": 0,
      "er_target": 0,
      "stage": "0.0",
      "board": "-",
      "specialty": "Cardiothoracic",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_12",
      "name": "د. حسين يحيى صبار",
      "notes": "",
      "dc_target": 2,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 3,
      "stage": "0.0",
      "board": "-",
      "specialty": "Cardiothoracic",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_13",
      "name": "د. منتظر صفاء ماجد",
      "notes": "",
      "dc_target": 2,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 3,
      "stage": "0.0",
      "board": "-",
      "specialty": "Cardiothoracic",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_14",
      "name": "د. امال سامي ثامر",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 2,
      "stage": "3.0",
      "board": "-",
      "specialty": "Dermatology",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_15",
      "name": "د. مروة محمد عبدالوهاب",
      "notes": "",
      "dc_target": 0,
      "con_target": 3,
      "rs_target": 1,
      "er_target": 0,
      "stage": "3.0",
      "board": "-",
      "specialty": "Dermatology",
      "sex": "F",
      "extra": 1
    },
    {
      "id": "res_16",
      "name": "د. علي وهاب سوادي",
      "notes": "",
      "dc_target": 0,
      "con_target": 2,
      "rs_target": 1,
      "er_target": 0,
      "stage": "3.0",
      "board": "-",
      "specialty": "Dermatology",
      "sex": "M",
      "extra": 1
    },
    {
      "id": "res_17",
      "name": "د. منتظر مؤيد حسين",
      "notes": "",
      "dc_target": 0,
      "con_target": 2,
      "rs_target": 1,
      "er_target": 0,
      "stage": "3.0",
      "board": "-",
      "specialty": "Dermatology",
      "sex": "M",
      "extra": 1
    },
    {
      "id": "res_18",
      "name": "د. رفل علي رسمي",
      "notes": "",
      "dc_target": 0,
      "con_target": 3,
      "rs_target": 1,
      "er_target": 0,
      "stage": "2.0",
      "board": "-",
      "specialty": "Dermatology",
      "sex": "F",
      "extra": 1
    },
    {
      "id": "res_19",
      "name": "د. زهراء قتيبة عبد",
      "notes": "",
      "dc_target": 0,
      "con_target": 3,
      "rs_target": 1,
      "er_target": 0,
      "stage": "2.0",
      "board": "-",
      "specialty": "Dermatology",
      "sex": "F",
      "extra": 1
    },
    {
      "id": "res_20",
      "name": "د. علي حسن خريبط",
      "notes": "",
      "dc_target": 0,
      "con_target": 3,
      "rs_target": 1,
      "er_target": 0,
      "stage": "2.0",
      "board": "-",
      "specialty": "Dermatology",
      "sex": "M",
      "extra": 1
    },
    {
      "id": "res_21",
      "name": "د. زين العابدين مصطفى محمد",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "1.0",
      "board": "Arabic",
      "specialty": "ENT",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_22",
      "name": "د. زهراء احمد عبدالكاظم",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 8,
      "stage": "-",
      "board": "-",
      "specialty": "Emergency",
      "sex": "F",
      "extra": 1
    },
    {
      "id": "res_23",
      "name": "د. ايات عباس مطشر",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "2.0",
      "board": "Arabic",
      "specialty": "ENT",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_24",
      "name": "د. زينب عبدالكريم احمد غانم",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "2.0",
      "board": "",
      "specialty": "ENT",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_25",
      "name": "د. فاطمة صبيح صاحب",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "2.0",
      "board": "",
      "specialty": "ENT",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_26",
      "name": "د. دعاء علي مجيد",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "2.0",
      "board": "",
      "specialty": "ENT",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_27",
      "name": "د. مصطفى عبدالصاحب",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "4.0",
      "board": "Arabic",
      "specialty": "ENT",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_28",
      "name": "د. مايا عادل عبدالهادي",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 1,
      "stage": "3.0",
      "board": "Arabic",
      "specialty": "ENT",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_29",
      "name": "د. ام البنين عيدان كاظم",
      "notes": "Already has 15 duties in her own specialty",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "2.0",
      "board": "Arabic",
      "specialty": "ENT",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_30",
      "name": "د. دنيا فارس حسون",
      "notes": "HAS EXTRA ER",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 4,
      "stage": "2.0",
      "board": "Iraqi",
      "specialty": "Family Medicine",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_31",
      "name": "د. زهراء كريم صالح",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "0.0",
      "board": "-",
      "specialty": "Family Medicine",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_32",
      "name": "د. فرح علي عبدالحسين",
      "notes": "",
      "dc_target": 0,
      "con_target": 2,
      "rs_target": 0,
      "er_target": 4,
      "stage": "0.0",
      "board": "-",
      "specialty": "Family Medicine",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_33",
      "name": "د. رسل سامي راضي",
      "notes": "(Dr. Ali Jawad's Wife) Consultatory in the holidays",
      "dc_target": 0,
      "con_target": 4,
      "rs_target": 0,
      "er_target": 0,
      "stage": "0.0",
      "board": "-",
      "specialty": "Family Medicine",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_34",
      "name": "د. الحسين جاسب فاخر",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 1,
      "stage": "4.0",
      "board": "Iraqi",
      "specialty": "General surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_35",
      "name": "د. محمد هاشم خضير",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 1,
      "stage": "4.0",
      "board": "Arabic",
      "specialty": "General surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_36",
      "name": "د. فاطمة فاضل كاظم",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 1,
      "stage": "3.0",
      "board": "Iraqi",
      "specialty": "General surgery",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_37",
      "name": "د. كرار علي زغير",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 1,
      "stage": "3.0",
      "board": "Iraqi",
      "specialty": "General surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_38",
      "name": "د. نجم هدو راضي",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 1,
      "stage": "3.0",
      "board": "Arabic",
      "specialty": "General surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_39",
      "name": "د. براء حسن عبدالهادي",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 2,
      "stage": "2.0",
      "board": "Arabic",
      "specialty": "General surgery",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_40",
      "name": "د. علي جميل حنتوش",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 2,
      "stage": "2.0",
      "board": "Arabic",
      "specialty": "General surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_41",
      "name": "د. خالد ابراهيم عبدالقادر",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "2.0",
      "board": "Arabic",
      "specialty": "General surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_42",
      "name": "د. حازم عبدالواحد محمد",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 2,
      "stage": "2.0",
      "board": "Arabic",
      "specialty": "General Surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_43",
      "name": "د. احمد الراوي",
      "notes": "",
      "dc_target": 2,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 2,
      "stage": "1.0",
      "board": "",
      "specialty": "General surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_44",
      "name": "د. احمد حارث عبدالمحسن",
      "notes": "",
      "dc_target": 2,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 2,
      "stage": "1.0",
      "board": "Arabic",
      "specialty": "General surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_45",
      "name": "د. رافع احمد عاشور",
      "notes": "PRIMARY EXAMINATION",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "1.0",
      "board": "Arabic",
      "specialty": "General surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_46",
      "name": "د. محمد حيدر باقر",
      "notes": "PRIMARY EXAMINATION",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "1.0",
      "board": "-",
      "specialty": "General surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_47",
      "name": "د. محمد فتحي عبدالرزاق",
      "notes": "PRIMARY EXAMINATION",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "1.0",
      "board": "-",
      "specialty": "General surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_48",
      "name": "د. سعيد جندي لهمود",
      "notes": "PRIMARY EXAMINATION",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "1.0",
      "board": "-",
      "specialty": "General surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_49",
      "name": "د. هبة سعدون مجبل",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 2,
      "stage": "0.0",
      "board": "",
      "specialty": "GP",
      "sex": "F",
      "extra": 1
    },
    {
      "id": "res_50",
      "name": "د. وفاء عبدالعال جدوع",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 2,
      "stage": "0.0",
      "board": "",
      "specialty": "GP",
      "sex": "F",
      "extra": 1
    },
    {
      "id": "res_51",
      "name": "د. منى عبدالباري",
      "notes": "",
      "dc_target": 0,
      "con_target": 3,
      "rs_target": 0,
      "er_target": 0,
      "stage": "0.0",
      "board": "",
      "specialty": "GP",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_52",
      "name": "د. احمد ناصرقاسم",
      "notes": "",
      "dc_target": 0,
      "con_target": 2,
      "rs_target": 0,
      "er_target": 0,
      "stage": "0.0",
      "board": "",
      "specialty": "GP",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_53",
      "name": "د. نورة فالح كاطع",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 2,
      "stage": "2.0",
      "board": "Arabic",
      "specialty": "Haematology",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_54",
      "name": "د. ايمان نعيم خيول",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 2,
      "stage": "2.0",
      "board": "",
      "specialty": "Internal Medicine",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_55",
      "name": "د. عيسى وليد عيسى",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 2,
      "stage": "1.0",
      "board": "Iraqi",
      "specialty": "Internal Medicine",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_56",
      "name": "د. ياسر علي فاضل",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "0.0",
      "board": "-",
      "specialty": "Internal Medicine",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_57",
      "name": "د. منتظر حميد هاشم",
      "notes": "In another hospital",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 1,
      "stage": "1.0",
      "board": "Iraqi",
      "specialty": "Internal Medicine",
      "sex": "M",
      "extra": 1
    },
    {
      "id": "res_58",
      "name": "د. محمد راضي خضر",
      "notes": "HIDE (NO MORE IN THE IRAQI HOSP. 😔)",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "4.0",
      "board": "Arabic",
      "specialty": "Neurosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_59",
      "name": "د. علي عبد ماضي",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 1,
      "stage": "4.0",
      "board": "Arabic",
      "specialty": "Neurosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_60",
      "name": "د. عبدالرحمن صفاء",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "4.0",
      "board": "Arabic",
      "specialty": "Neurosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_61",
      "name": "د. يوسف علي يوسف",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 1,
      "stage": "4.0",
      "board": "Arabic",
      "specialty": "Neurosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_62",
      "name": "د. فاطمة خليل",
      "notes": "",
      "dc_target": 2,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 1,
      "stage": "3.0",
      "board": "Iraqi",
      "specialty": "Neurosurgery",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_63",
      "name": "د. ليث انور",
      "notes": "",
      "dc_target": 2,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 1,
      "stage": "3.0",
      "board": "Iraqi",
      "specialty": "Neurosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_64",
      "name": "د. محمد رياض جعفر",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "3.0",
      "board": "Arabic",
      "specialty": "Neurosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_65",
      "name": "د. سرمد نوفل",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "2.0",
      "board": "Arabic",
      "specialty": "Neurosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_66",
      "name": "د. احمد عبدالله حسن",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "2.0",
      "board": "Iraqi",
      "specialty": "Neurosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_67",
      "name": "د. اسعد حسن فرحان",
      "notes": "",
      "dc_target": 2,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 2,
      "stage": "2.0",
      "board": "Iraqi",
      "specialty": "Neurosurgery",
      "sex": "M",
      "extra": 1
    },
    {
      "id": "res_68",
      "name": "د. محمد عبدالحسين محسن",
      "notes": "",
      "dc_target": 2,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 2,
      "stage": "2.0",
      "board": "Arabic",
      "specialty": "Neurosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_69",
      "name": "د. علي مهدي منصور",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 2,
      "stage": "1.0",
      "board": "Iraqi",
      "specialty": "Neurosurgery",
      "sex": "M",
      "extra": 1
    },
    {
      "id": "res_70",
      "name": "د. نور الهدى عضيد",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 1,
      "stage": "4.0",
      "board": "-",
      "specialty": "Oncology",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_71",
      "name": "د. صفاء كاظم حسن",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "0.0",
      "board": "",
      "specialty": "Oncology",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_72",
      "name": "د. خيرية شهد عكلة",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 1,
      "stage": "4.0",
      "board": "Arabic",
      "specialty": "Oncology",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_73",
      "name": "د. فاطمة مضر علي",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 3,
      "stage": "0.0",
      "board": "-",
      "specialty": "Oncology",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_74",
      "name": "د. هبة اياد طارق",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "3.0",
      "board": "Arabic",
      "specialty": "Plastic surgery",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_75",
      "name": "د. حميدة حبيب عباس",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 3,
      "stage": "0.0",
      "board": "-",
      "specialty": "Oncology",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_76",
      "name": "د. حنين علي عبدالصمد",
      "notes": "GP",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 2,
      "stage": "0.0",
      "board": "-",
      "specialty": "GP",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_77",
      "name": "د. علي ياسين محمد",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "3.0",
      "board": "Iraqi",
      "specialty": "Cardiothoracic",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_78",
      "name": "د. عبدالحليم حسن موسى",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "2.0",
      "board": "Iraqi",
      "specialty": "Cardiothoracic",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_79",
      "name": "د. زهراء سهيل نجم",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 3,
      "stage": "0.0",
      "board": "-",
      "specialty": "Oncology",
      "sex": "F",
      "extra": 1
    },
    {
      "id": "res_80",
      "name": "د. سارة عدنان مالك",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "-",
      "board": "-",
      "specialty": "Family Medicine",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_81",
      "name": "د. مريم سالم جارالله",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "-",
      "board": "-",
      "specialty": "Family Medicine",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_82",
      "name": "د. سحر فالح حسن",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "2.0",
      "board": "Iraqi",
      "specialty": "Family Medicine",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_83",
      "name": "د. احمد خضر بجاي",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "3.0",
      "board": "Arabic",
      "specialty": "General Surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_84",
      "name": "د. فهد يوسف عبدالله",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "3.0",
      "board": "Arabic",
      "specialty": "General surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_85",
      "name": "د. حسنين فيصل",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "3.0",
      "board": "Arabic",
      "specialty": "General surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_86",
      "name": "د. دعاء كريم",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "3.0",
      "board": "",
      "specialty": "General surgery",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_87",
      "name": "د. ماهر محمود عبدالله",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "3.0",
      "board": "Arabic",
      "specialty": "General surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_88",
      "name": "د. علي عبدالامير",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "3.0",
      "board": "Arabic",
      "specialty": "General Surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_89",
      "name": "د. مروة ليث",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 3,
      "stage": "0.0",
      "board": "",
      "specialty": "Oncology",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_90",
      "name": "د. محمد محروس علي",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "",
      "board": "",
      "specialty": "General Surgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_91",
      "name": "د. قنوت حيدر كاظم",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "",
      "board": "Arabic",
      "specialty": "General surgery",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_92",
      "name": "د. أيام زاهر عبدالمجيد",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "3.0",
      "board": "-",
      "specialty": "Internal Medicine",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_93",
      "name": "د. عبدالرحمن محمد مكي",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "3.0",
      "board": "-",
      "specialty": "Internal Medicine",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_94",
      "name": "د. دعاء نبيل عبدالجليل",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "2.0",
      "board": "",
      "specialty": "Internal medicine",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_95",
      "name": "د. احرار غانم نوري",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "2.0",
      "board": "",
      "specialty": "Internal medicine",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_96",
      "name": "د. بشير كريم مهنا",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "2.0",
      "board": "Iraqi",
      "specialty": "Internal Medicine",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_97",
      "name": "د. علا طالب عبدالامير",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "1.0",
      "board": "",
      "specialty": "Internal Medicine",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_98",
      "name": "د. زهراء عماد خضير",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "1.0",
      "board": "",
      "specialty": "Internal Medicine",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_99",
      "name": "د. وسن عباس عبدالكريم",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "1.0",
      "board": "",
      "specialty": "Internal Medicine",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_100",
      "name": "د. احمد عبدالزهرة طه",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "",
      "board": "",
      "specialty": "Internal Medicine",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_101",
      "name": "د. مهاجر زياد راشد",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "",
      "board": "Arabic",
      "specialty": "Internal Medicine",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_102",
      "name": "د. ام البنين عبدالله عبدالحسين",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "",
      "board": "",
      "specialty": "Internal Medicine",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_103",
      "name": "د. مريم مشرق ياسين",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 3,
      "stage": "0.0",
      "board": "-",
      "specialty": "Oncology",
      "sex": "F",
      "extra": 1
    },
    {
      "id": "res_104",
      "name": "د. اياد يعرب",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "3.0",
      "board": "Arabic",
      "specialty": "Neurosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_105",
      "name": "د. نور الهدى عادل عبدالله",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 3,
      "stage": "0.0",
      "board": "",
      "specialty": "Oncology",
      "sex": "F",
      "extra": 1
    },
    {
      "id": "res_106",
      "name": "د. علي اسعد يحيى",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 3,
      "stage": "0.0",
      "board": "-",
      "specialty": "Oncology",
      "sex": "M",
      "extra": 1
    },
    {
      "id": "res_107",
      "name": "د. احمد مرتضى جواد",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 4,
      "stage": "0.0",
      "board": "-",
      "specialty": "Oncology",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_108",
      "name": "د. الحسن حسين جبار",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "1.0",
      "board": "-",
      "specialty": "Neurosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_109",
      "name": "د. علي عارف",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "1.0",
      "board": "Arabic",
      "specialty": "Neurosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_110",
      "name": "د. مجيد حميد مجيد",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "1.0",
      "board": "Arabic",
      "specialty": "Neurosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_111",
      "name": "د. علي محمد احمد",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 3,
      "stage": "",
      "board": "Arabic",
      "specialty": "Oncology",
      "sex": "M",
      "extra": 1
    },
    {
      "id": "res_112",
      "name": "د. عمار صلاح",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "",
      "board": "",
      "specialty": "Neurosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_113",
      "name": "د. أحمد علي يحيى",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "-",
      "board": "",
      "specialty": "Oncology",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_114",
      "name": "د. عباس احمد رجب",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "3.0",
      "board": "Arabic",
      "specialty": "Oncology",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_115",
      "name": "د. محمد شاكر",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 2,
      "stage": "0.0",
      "board": "-",
      "specialty": "Ophthalmology",
      "sex": "M",
      "extra": 1
    },
    {
      "id": "res_116",
      "name": "د. محمد عماد جميل",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 2,
      "stage": "0.0",
      "board": "-",
      "specialty": "Ophthalmology",
      "sex": "M",
      "extra": 1
    },
    {
      "id": "res_117",
      "name": "د. حسين علي جبار",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "-",
      "board": "-",
      "specialty": "Orthopaedics",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_118",
      "name": "د. زهير فائق صادق",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "",
      "board": "",
      "specialty": "Orthopaedics",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_119",
      "name": "د. حسين ابراهيم علي",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "",
      "board": "",
      "specialty": "Orthopaedics",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_120",
      "name": "د. علي ضياء عبدالنبي",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "",
      "board": "",
      "specialty": "Orthopaedics",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_121",
      "name": "د. محمد ليث عباس",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "",
      "board": "",
      "specialty": "Orthopaedics",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_122",
      "name": "د. حسين عبدالامير كاطع",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "",
      "board": "",
      "specialty": "Orthopaedics",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_123",
      "name": "د. طه مشتاق",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "",
      "board": "",
      "specialty": "Orthopaedics",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_124",
      "name": "د. نور خالد طارش",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "2.0",
      "board": "",
      "specialty": "Plastic surgery",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_125",
      "name": "د. زهراء توفيق عبدالله",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "",
      "board": "Arabic",
      "specialty": "Plastic surgery",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_126",
      "name": "د. غفران محمد خلف",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "",
      "board": "Arabic",
      "specialty": "Plastic surgery",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_127",
      "name": "د. نازك احمد ماجد",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "1.0",
      "board": "Arabic",
      "specialty": "Radiology",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_128",
      "name": "د. زينب جبار محسن",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "1.0",
      "board": "Arabic",
      "specialty": "Radiology",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_129",
      "name": "د. احمد حسين علي",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "FINAL",
      "board": "",
      "specialty": "Urosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_130",
      "name": "د. رسل منذر خليل",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "1.0",
      "board": "Arabic",
      "specialty": "Plastic surgery",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_131",
      "name": "د. هبة اياد طارق",
      "notes": "HIDE",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "1.0",
      "board": "Arabic",
      "specialty": "Plastic surgery",
      "sex": "F",
      "extra": 0
    },
    {
      "id": "res_132",
      "name": "د. احمد كريم غتر",
      "notes": "PRIMARY EXAMINATION",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 0,
      "stage": "2.0",
      "board": "-",
      "specialty": "Urosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_133",
      "name": "د. ضرغام عامر حسان",
      "notes": "",
      "dc_target": 2,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 2,
      "stage": "2.0",
      "board": "Arabic",
      "specialty": "Urosurgery",
      "sex": "M",
      "extra": 1
    },
    {
      "id": "res_134",
      "name": "د. مرتضى امين عبدالحضر",
      "notes": "",
      "dc_target": 2,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 2,
      "stage": "1.0",
      "board": "Arabic",
      "specialty": "Urosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_135",
      "name": "د. عذراء صبيح بدر",
      "notes": "",
      "dc_target": 2,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 2,
      "stage": "1.0",
      "board": "Arabic",
      "specialty": "Urosurgery",
      "sex": "F",
      "extra": 1
    },
    {
      "id": "res_136",
      "name": "د. علي عقيل عبد",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 2,
      "stage": "1.0",
      "board": "Arabic",
      "specialty": "Urosurgery",
      "sex": "M",
      "extra": 1
    },
    {
      "id": "res_137",
      "name": "د. علي صباح كاظم",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 2,
      "stage": "1.0",
      "board": "Arabic",
      "specialty": "Urosurgery",
      "sex": "M",
      "extra": 1
    },
    {
      "id": "res_138",
      "name": "د. عبدالله عبدالمجيد ماضي",
      "notes": "",
      "dc_target": 2,
      "con_target": 0,
      "rs_target": 0,
      "er_target": 3,
      "stage": "0.0",
      "board": "-",
      "specialty": "Urosurgery",
      "sex": "M",
      "extra": 0
    },
    {
      "id": "res_139",
      "name": "د. عادل ناصر",
      "notes": "",
      "dc_target": 0,
      "con_target": 0,
      "rs_target": 1,
      "er_target": 0,
      "stage": "2.0",
      "board": "Arabic",
      "specialty": "Cardiothoracic",
      "sex": "M",
      "extra": 1
    }
  ],
  "schedules": {
    "er": [
      {
        "dayNumber": 1,
        "date": "2026-09-01",
        "dayName": "الثلاثاء",
        "morning": "د. دنيا فارس حسون",
        "afternoon": "د. فاطمة فاضل كاظم",
        "preNight": "د. ضرغام عامر حسان",
        "lateNight": "د. محمد شاكر",
        "notes": ""
      },
      {
        "dayNumber": 2,
        "date": "2026-09-02",
        "dayName": "الأربعاء",
        "morning": "د. زهراء احمد عبدالكاظم",
        "afternoon": "د. نور الهدى عادل عبدالله",
        "preNight": "د. نجم هدو راضي",
        "lateNight": "د. عبدالله عبدالمجيد ماضي",
        "notes": ""
      },
      {
        "dayNumber": 3,
        "date": "2026-09-03",
        "dayName": "الخميس",
        "morning": "د. زهراء احمد عبدالكاظم",
        "afternoon": "د. امال سامي ثامر",
        "preNight": "د. اسعد حسن فرحان",
        "lateNight": "د. محمد هاشم خضير",
        "notes": ""
      },
      {
        "dayNumber": 4,
        "date": "2026-09-04",
        "dayName": "الجمعة",
        "morning": "د. ايمان نعيم خيول",
        "afternoon": "د. مريم مشرق ياسين",
        "preNight": "د. احمد مرتضى جواد",
        "lateNight": "د. عماد سمير عبدالرضا",
        "notes": ""
      },
      {
        "dayNumber": 5,
        "date": "2026-09-05",
        "dayName": "السبت",
        "morning": "د. نورة فالح كاطع",
        "afternoon": "د. عذراء صبيح بدر",
        "preNight": "د. علي اسعد يحيى",
        "lateNight": "د. منتظر حميد هاشم",
        "notes": ""
      },
      {
        "dayNumber": 6,
        "date": "2026-09-06",
        "dayName": "الأحد",
        "morning": "د. هبة سعدون مجبل",
        "afternoon": "د. دنيا فارس حسون",
        "preNight": "د. منتظر صفاء ماجد",
        "lateNight": "د. ضرغام عامر حسان",
        "notes": ""
      },
      {
        "dayNumber": 7,
        "date": "2026-09-07",
        "dayName": "الاثنين",
        "morning": "د. زهراء احمد عبدالكاظم",
        "afternoon": "د. فاطمة خليل",
        "preNight": "د. احمد حارث عبدالمحسن",
        "lateNight": "د. كرار علي زغير",
        "notes": "كرار نايت بدل ايهاب"
      },
      {
        "dayNumber": 8,
        "date": "2026-09-08",
        "dayName": "الثلاثاء",
        "morning": "د. وفاء عبدالعال جدوع",
        "afternoon": "د. نور الهدى عادل عبدالله",
        "preNight": "د. ليث انور",
        "lateNight": "د. علي صباح كاظم",
        "notes": ""
      },
      {
        "dayNumber": 9,
        "date": "2026-09-09",
        "dayName": "الأربعاء",
        "morning": "د. احمد مرتضى جواد",
        "afternoon": "د. براء حسن عبدالهادي",
        "preNight": "د. مرتضى امين عبدالحضر",
        "lateNight": "د. علي مهدي منصور",
        "notes": ""
      },
      {
        "dayNumber": 10,
        "date": "2026-09-10",
        "dayName": "الخميس",
        "morning": "د. دنيا فارس حسون",
        "afternoon": "د. فاطمة مضر علي",
        "preNight": "د. محمد شاكر",
        "lateNight": "د. علي محمد احمد",
        "notes": ""
      },
      {
        "dayNumber": 11,
        "date": "2026-09-11",
        "dayName": "الجمعة",
        "morning": "د. فرح علي عبدالحسين",
        "afternoon": "د. علي عبدالرحمن عبدالصمد",
        "preNight": "د. احمد مرتضى جواد",
        "lateNight": "د. الحسين جاسب فاخر",
        "notes": ""
      },
      {
        "dayNumber": 12,
        "date": "2026-09-12",
        "dayName": "السبت",
        "morning": "د. مريم مشرق ياسين",
        "afternoon": "د. فاطمة مضر علي",
        "preNight": "د. حازم عبدالواحد محمد",
        "lateNight": "د. احمد حارث عبدالمحسن",
        "notes": ""
      },
      {
        "dayNumber": 13,
        "date": "2026-09-13",
        "dayName": "الأحد",
        "morning": "د. زهراء احمد عبدالكاظم",
        "afternoon": "د. حميدة حبيب عباس",
        "preNight": "د. حسين يحيى صبار",
        "lateNight": "د. اسعد حسن فرحان",
        "notes": ""
      },
      {
        "dayNumber": 14,
        "date": "2026-09-14",
        "dayName": "الاثنين",
        "morning": "د. حنين علي عبدالصمد",
        "afternoon": "د. امال سامي ثامر",
        "preNight": "د. علي جميل حنتوش",
        "lateNight": "د. احمد مرتضى جواد",
        "notes": ""
      },
      {
        "dayNumber": 15,
        "date": "2026-09-15",
        "dayName": "الثلاثاء",
        "morning": "د. وفاء عبدالعال جدوع",
        "afternoon": "د. مروة ليث",
        "preNight": "د. عماد سمير عبدالرضا",
        "lateNight": "د. علي اسعد يحيى",
        "notes": ""
      },
      {
        "dayNumber": 16,
        "date": "2026-09-16",
        "dayName": "الأربعاء",
        "morning": "د. فرح علي عبدالحسين",
        "afternoon": "د. حميدة حبيب عباس",
        "preNight": "د. علي محمد احمد",
        "lateNight": "د. ايهاب عبدالكريم غالب",
        "notes": ""
      },
      {
        "dayNumber": 17,
        "date": "2026-09-17",
        "dayName": "الخميس",
        "morning": "د. زهراء احمد عبدالكاظم",
        "afternoon": "د. عذراء صبيح بدر",
        "preNight": "د. محمد عبدالحسين محسن",
        "lateNight": "د. يوسف علي يوسف",
        "notes": ""
      },
      {
        "dayNumber": 18,
        "date": "2026-09-18",
        "dayName": "الجمعة",
        "morning": "د. فرح علي عبدالحسين",
        "afternoon": "د. مروة ليث",
        "preNight": "د. علي عبدالرحمن عبدالصمد",
        "lateNight": "د. ايهاب عبدالكريم غالب",
        "notes": "ايهاب نايت بدل كرار"
      },
      {
        "dayNumber": 19,
        "date": "2026-09-19",
        "dayName": "السبت",
        "morning": "د. نور الهدى عضيد",
        "afternoon": "د. ايمان نعيم خيول",
        "preNight": "د. محمد عماد جميل",
        "lateNight": "د. احمد الراوي",
        "notes": ""
      },
      {
        "dayNumber": 20,
        "date": "2026-09-20",
        "dayName": "الأحد",
        "morning": "د. دنيا فارس حسون",
        "afternoon": "د. نور الهدى عادل عبدالله",
        "preNight": "د. عبدالله عبدالمجيد ماضي",
        "lateNight": "د. منتظر صفاء ماجد",
        "notes": ""
      },
      {
        "dayNumber": 21,
        "date": "2026-09-21",
        "dayName": "الاثنين",
        "morning": "د. زهراء احمد عبدالكاظم",
        "afternoon": "د. براء حسن عبدالهادي",
        "preNight": "د. حازم عبدالواحد محمد",
        "lateNight": "د. محمد عماد جميل",
        "notes": ""
      },
      {
        "dayNumber": 22,
        "date": "2026-09-22",
        "dayName": "الثلاثاء",
        "morning": "د. زهراء سهيل نجم",
        "afternoon": "د. فاطمة مضر علي",
        "preNight": "د. علي محمد احمد",
        "lateNight": "د. علي اسعد يحيى",
        "notes": ""
      },
      {
        "dayNumber": 23,
        "date": "2026-09-23",
        "dayName": "الأربعاء",
        "morning": "د. هبة سعدون مجبل",
        "afternoon": "د. عيسى وليد عيسى",
        "preNight": "د. ايهاب عبدالكريم غالب",
        "lateNight": "د. حسين يحيى صبار",
        "notes": ""
      },
      {
        "dayNumber": 24,
        "date": "2026-09-24",
        "dayName": "الخميس",
        "morning": "د. زهراء احمد عبدالكاظم",
        "afternoon": "د. مروة ليث",
        "preNight": "د. محمد عبدالحسين محسن",
        "lateNight": "د. علي عبد ماضي",
        "notes": ""
      },
      {
        "dayNumber": 25,
        "date": "2026-09-25",
        "dayName": "الجمعة",
        "morning": "د. خيرية شهد عكلة",
        "afternoon": "د. حميدة حبيب عباس",
        "preNight": "د. علي حسين عبدالرضا",
        "lateNight": "د. علي عقيل عبد",
        "notes": ""
      },
      {
        "dayNumber": 26,
        "date": "2026-09-26",
        "dayName": "السبت",
        "morning": "د. عبدالله عبدالمجيد ماضي",
        "afternoon": "د. نورة فالح كاطع",
        "preNight": "د. علي عبدالرحمن عبدالصمد",
        "lateNight": "د. احمد الراوي",
        "notes": ""
      },
      {
        "dayNumber": 27,
        "date": "2026-09-27",
        "dayName": "الأحد",
        "morning": "د. زهراء سهيل نجم",
        "afternoon": "د. مريم مشرق ياسين",
        "preNight": "د. علي مهدي منصور",
        "lateNight": "د. منتظر صفاء ماجد",
        "notes": ""
      },
      {
        "dayNumber": 28,
        "date": "2026-09-28",
        "dayName": "الاثنين",
        "morning": "د. زهراء احمد عبدالكاظم",
        "afternoon": "د. حسين يحيى صبار",
        "preNight": "د. علي عقيل عبد",
        "lateNight": "د. علي جميل حنتوش",
        "notes": ""
      },
      {
        "dayNumber": 29,
        "date": "2026-09-29",
        "dayName": "الثلاثاء",
        "morning": "د. زهراء سهيل نجم",
        "afternoon": "د. مايا عادل عبدالهادي",
        "preNight": "د. عيسى وليد عيسى",
        "lateNight": "د. مرتضى امين عبدالحضر",
        "notes": ""
      },
      {
        "dayNumber": 30,
        "date": "2026-09-30",
        "dayName": "الأربعاء",
        "morning": "د. حنين علي عبدالصمد",
        "afternoon": "د. فرح علي عبدالحسين",
        "preNight": "د. علي صباح كاظم",
        "lateNight": "د. علي حسين عبدالرضا",
        "notes": ""
      },
      {
        "dayNumber": 1,
        "date": "2026-10-01",
        "dayName": "الخميس",
        "morning": "",
        "afternoon": "",
        "preNight": "",
        "lateNight": "",
        "notes": ""
      }
    ],
    "con": [
      {
        "dayNumber": 1,
        "date": "2026-09-01",
        "dayName": "الثلاثاء",
        "doctor": "د. مروة محمد عبدالوهاب"
      },
      {
        "dayNumber": 2,
        "date": "2026-09-02",
        "dayName": "الأربعاء",
        "doctor": "د. زهراء قتيبة عبد"
      },
      {
        "dayNumber": 3,
        "date": "2026-09-03",
        "dayName": "الخميس",
        "doctor": "د. همام حبيب عبدالله"
      },
      {
        "dayNumber": 4,
        "date": "2026-09-04",
        "dayName": "الجمعة",
        "doctor": "د. رسل سامي راضي"
      },
      {
        "dayNumber": 5,
        "date": "2026-09-05",
        "dayName": "السبت",
        "doctor": "د. علي حسن خريبط"
      },
      {
        "dayNumber": 6,
        "date": "2026-09-06",
        "dayName": "الأحد",
        "doctor": "د. مروة محمد عبدالوهاب"
      },
      {
        "dayNumber": 7,
        "date": "2026-09-07",
        "dayName": "الاثنين",
        "doctor": "د. همام حبيب عبدالله"
      },
      {
        "dayNumber": 8,
        "date": "2026-09-08",
        "dayName": "الثلاثاء",
        "doctor": "د. علي وهاب سوادي"
      },
      {
        "dayNumber": 9,
        "date": "2026-09-09",
        "dayName": "الأربعاء",
        "doctor": "د. زهراء قتيبة عبد"
      },
      {
        "dayNumber": 10,
        "date": "2026-09-10",
        "dayName": "الخميس",
        "doctor": "د. علي حسن خريبط"
      },
      {
        "dayNumber": 11,
        "date": "2026-09-11",
        "dayName": "الجمعة",
        "doctor": "د. رسل سامي راضي"
      },
      {
        "dayNumber": 12,
        "date": "2026-09-12",
        "dayName": "السبت",
        "doctor": "د. فرح علي عبدالحسين"
      },
      {
        "dayNumber": 13,
        "date": "2026-09-13",
        "dayName": "الأحد",
        "doctor": "د. زهراء قتيبة عبد"
      },
      {
        "dayNumber": 14,
        "date": "2026-09-14",
        "dayName": "الاثنين",
        "doctor": "د. رفل علي رسمي"
      },
      {
        "dayNumber": 15,
        "date": "2026-09-15",
        "dayName": "الثلاثاء",
        "doctor": "د. علي وهاب سوادي"
      },
      {
        "dayNumber": 16,
        "date": "2026-09-16",
        "dayName": "الأربعاء",
        "doctor": "د. احمد ناصرقاسم"
      },
      {
        "dayNumber": 17,
        "date": "2026-09-17",
        "dayName": "الخميس",
        "doctor": "د. همام حبيب عبدالله"
      },
      {
        "dayNumber": 18,
        "date": "2026-09-18",
        "dayName": "الجمعة",
        "doctor": "د. رسل سامي راضي"
      },
      {
        "dayNumber": 19,
        "date": "2026-09-19",
        "dayName": "السبت",
        "doctor": "د. رفل علي رسمي"
      },
      {
        "dayNumber": 20,
        "date": "2026-09-20",
        "dayName": "الأحد",
        "doctor": "د. منتظر مؤيد حسين"
      },
      {
        "dayNumber": 21,
        "date": "2026-09-21",
        "dayName": "الاثنين",
        "doctor": "د. رفل علي رسمي"
      },
      {
        "dayNumber": 22,
        "date": "2026-09-22",
        "dayName": "الثلاثاء",
        "doctor": "د. احمد ناصرقاسم"
      },
      {
        "dayNumber": 23,
        "date": "2026-09-23",
        "dayName": "الأربعاء",
        "doctor": "د. منى عبدالباري"
      },
      {
        "dayNumber": 24,
        "date": "2026-09-24",
        "dayName": "الخميس",
        "doctor": "د. منتظر مؤيد حسين"
      },
      {
        "dayNumber": 25,
        "date": "2026-09-25",
        "dayName": "الجمعة",
        "doctor": "د. رسل سامي راضي"
      },
      {
        "dayNumber": 26,
        "date": "2026-09-26",
        "dayName": "السبت",
        "doctor": "د. فرح علي عبدالحسين"
      },
      {
        "dayNumber": 27,
        "date": "2026-09-27",
        "dayName": "الأحد",
        "doctor": "د. مروة محمد عبدالوهاب"
      },
      {
        "dayNumber": 28,
        "date": "2026-09-28",
        "dayName": "الاثنين",
        "doctor": "د. منى عبدالباري"
      },
      {
        "dayNumber": 29,
        "date": "2026-09-29",
        "dayName": "الثلاثاء",
        "doctor": "د. علي حسن خريبط"
      },
      {
        "dayNumber": 30,
        "date": "2026-09-30",
        "dayName": "الأربعاء",
        "doctor": "د. منى عبدالباري"
      },
      {
        "dayNumber": 1,
        "date": "2026-10-01",
        "dayName": "الخميس",
        "doctor": ""
      }
    ],
    "dc": [
      {
        "dayNumber": 1,
        "date": "2026-09-01",
        "dayName": "الثلاثاء",
        "doctor": "د. احمد حارث عبدالمحسن"
      },
      {
        "dayNumber": 2,
        "date": "2026-09-02",
        "dayName": "الأربعاء",
        "doctor": "د. مرتضى امين عبدالحضر"
      },
      {
        "dayNumber": 3,
        "date": "2026-09-03",
        "dayName": "الخميس",
        "doctor": "د. عبدالله عبدالمجيد ماضي"
      },
      {
        "dayNumber": 4,
        "date": "2026-09-04",
        "dayName": "الجمعة",
        "doctor": "د. علي عبدالرحمن عبدالصمد"
      },
      {
        "dayNumber": 5,
        "date": "2026-09-05",
        "dayName": "السبت",
        "doctor": "د. عماد سمير عبدالرضا"
      },
      {
        "dayNumber": 6,
        "date": "2026-09-06",
        "dayName": "الأحد",
        "doctor": "د. عذراء صبيح بدر"
      },
      {
        "dayNumber": 7,
        "date": "2026-09-07",
        "dayName": "الاثنين",
        "doctor": "د. حسين يحيى صبار"
      },
      {
        "dayNumber": 8,
        "date": "2026-09-08",
        "dayName": "الثلاثاء",
        "doctor": "د. محمد عبدالحسين محسن"
      },
      {
        "dayNumber": 9,
        "date": "2026-09-09",
        "dayName": "الأربعاء",
        "doctor": "د. احمد حارث عبدالمحسن"
      },
      {
        "dayNumber": 10,
        "date": "2026-09-10",
        "dayName": "الخميس",
        "doctor": "د. اسعد حسن فرحان"
      },
      {
        "dayNumber": 11,
        "date": "2026-09-11",
        "dayName": "الجمعة",
        "doctor": "د. ضرغام عامر حسان"
      },
      {
        "dayNumber": 12,
        "date": "2026-09-12",
        "dayName": "السبت",
        "doctor": "د. فاطمة خليل"
      },
      {
        "dayNumber": 13,
        "date": "2026-09-13",
        "dayName": "الأحد",
        "doctor": "د. عذراء صبيح بدر"
      },
      {
        "dayNumber": 14,
        "date": "2026-09-14",
        "dayName": "الاثنين",
        "doctor": "د. محمد عبدالحسين محسن"
      },
      {
        "dayNumber": 15,
        "date": "2026-09-15",
        "dayName": "الثلاثاء",
        "doctor": "د. اسعد حسن فرحان"
      },
      {
        "dayNumber": 16,
        "date": "2026-09-16",
        "dayName": "الأربعاء",
        "doctor": "د. عبدالله عبدالمجيد ماضي"
      },
      {
        "dayNumber": 17,
        "date": "2026-09-17",
        "dayName": "الخميس",
        "doctor": "د. احمد الراوي"
      },
      {
        "dayNumber": 18,
        "date": "2026-09-18",
        "dayName": "الجمعة",
        "doctor": "د. احمد الراوي"
      },
      {
        "dayNumber": 19,
        "date": "2026-09-19",
        "dayName": "السبت",
        "doctor": "د. منتظر صفاء ماجد"
      },
      {
        "dayNumber": 20,
        "date": "2026-09-20",
        "dayName": "الأحد",
        "doctor": "د. ايهاب عبدالكريم غالب"
      },
      {
        "dayNumber": 21,
        "date": "2026-09-21",
        "dayName": "الاثنين",
        "doctor": "د. مرتضى امين عبدالحضر"
      },
      {
        "dayNumber": 22,
        "date": "2026-09-22",
        "dayName": "الثلاثاء",
        "doctor": "د. عماد سمير عبدالرضا"
      },
      {
        "dayNumber": 23,
        "date": "2026-09-23",
        "dayName": "الأربعاء",
        "doctor": "د. علي عبدالرحمن عبدالصمد"
      },
      {
        "dayNumber": 24,
        "date": "2026-09-24",
        "dayName": "الخميس",
        "doctor": "د. حسين يحيى صبار"
      },
      {
        "dayNumber": 25,
        "date": "2026-09-25",
        "dayName": "الجمعة",
        "doctor": "د. ليث انور"
      },
      {
        "dayNumber": 26,
        "date": "2026-09-26",
        "dayName": "السبت",
        "doctor": "د. ايهاب عبدالكريم غالب"
      },
      {
        "dayNumber": 27,
        "date": "2026-09-27",
        "dayName": "الأحد",
        "doctor": "د. فاطمة خليل"
      },
      {
        "dayNumber": 28,
        "date": "2026-09-28",
        "dayName": "الاثنين",
        "doctor": "د. ضرغام عامر حسان"
      },
      {
        "dayNumber": 29,
        "date": "2026-09-29",
        "dayName": "الثلاثاء",
        "doctor": "د. منتظر صفاء ماجد"
      },
      {
        "dayNumber": 30,
        "date": "2026-09-30",
        "dayName": "الأربعاء",
        "doctor": "د. ليث انور"
      },
      {
        "dayNumber": 1,
        "date": "2026-10-01",
        "dayName": "الخميس",
        "doctor": ""
      }
    ],
    "rs": [
      {
        "dayNumber": 1,
        "date": "2026-09-01",
        "dayName": "الثلاثاء",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 2,
        "date": "2026-09-02",
        "dayName": "الأربعاء",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 3,
        "date": "2026-09-03",
        "dayName": "الخميس",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 4,
        "date": "2026-09-04",
        "dayName": "الجمعة",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 5,
        "date": "2026-09-05",
        "dayName": "السبت",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 6,
        "date": "2026-09-06",
        "dayName": "الأحد",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 7,
        "date": "2026-09-07",
        "dayName": "الاثنين",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 8,
        "date": "2026-09-08",
        "dayName": "الثلاثاء",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 9,
        "date": "2026-09-09",
        "dayName": "الأربعاء",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 10,
        "date": "2026-09-10",
        "dayName": "الخميس",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 11,
        "date": "2026-09-11",
        "dayName": "الجمعة",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 12,
        "date": "2026-09-12",
        "dayName": "السبت",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 13,
        "date": "2026-09-13",
        "dayName": "الأحد",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 14,
        "date": "2026-09-14",
        "dayName": "الاثنين",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 15,
        "date": "2026-09-15",
        "dayName": "الثلاثاء",
        "er_lateNight": "د. علي مهدي منصور",
        "er_preNight": "د. عادل ناصر",
        "er_afternoon": "د. محمد عماد جميل",
        "er_morning": "د. عذراء صبيح بدر",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 16,
        "date": "2026-09-16",
        "dayName": "الأربعاء",
        "er_lateNight": "د. منتظر حميد هاشم",
        "er_preNight": "د. محمد شاكر",
        "er_afternoon": "د. اسعد حسن فرحان",
        "er_morning": "د. وفاء عبدالعال جدوع",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 17,
        "date": "2026-09-17",
        "dayName": "الخميس",
        "er_lateNight": "د. علي اسعد يحيى",
        "er_preNight": "د. علي وهاب سوادي",
        "er_afternoon": "د. نور الهدى عادل عبدالله",
        "er_morning": "د. هبة سعدون مجبل",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 18,
        "date": "2026-09-18",
        "dayName": "الجمعة",
        "er_lateNight": "د. علي حسن خريبط",
        "er_preNight": "د. علي محمد احمد",
        "er_afternoon": "د. رفل علي رسمي",
        "er_morning": "د. زهراء قتيبة عبد",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 19,
        "date": "2026-09-19",
        "dayName": "السبت",
        "er_lateNight": "د. علي صباح كاظم",
        "er_preNight": "د. منتظر مؤيد حسين",
        "er_afternoon": "د. مريم مشرق ياسين",
        "er_morning": "د. مروة محمد عبدالوهاب",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 20,
        "date": "2026-09-20",
        "dayName": "الأحد",
        "er_lateNight": "د. علي عقيل عبد",
        "er_preNight": "د. ضرغام عامر حسان",
        "er_afternoon": "د. زهراء سهيل نجم",
        "er_morning": "د. زهراء احمد عبدالكاظم",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 21,
        "date": "2026-09-21",
        "dayName": "الاثنين",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 22,
        "date": "2026-09-22",
        "dayName": "الثلاثاء",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 23,
        "date": "2026-09-23",
        "dayName": "الأربعاء",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 24,
        "date": "2026-09-24",
        "dayName": "الخميس",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 25,
        "date": "2026-09-25",
        "dayName": "الجمعة",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 26,
        "date": "2026-09-26",
        "dayName": "السبت",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 27,
        "date": "2026-09-27",
        "dayName": "الأحد",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 28,
        "date": "2026-09-28",
        "dayName": "الاثنين",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 29,
        "date": "2026-09-29",
        "dayName": "الثلاثاء",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 30,
        "date": "2026-09-30",
        "dayName": "الأربعاء",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      },
      {
        "dayNumber": 1,
        "date": "2026-10-01",
        "dayName": "الخميس",
        "er_lateNight": "",
        "er_preNight": "",
        "er_afternoon": "",
        "er_morning": "",
        "ward_private": "",
        "ward_floor4": "",
        "ward_floor5": ""
      }
    ]
  }
};
